//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMetroidRandomizer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SM Random - <seed>.sfc")]
        public string OutputFile {
            get {
                return ((string)(this["OutputFile"]));
            }
            set {
                this["OutputFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SM Random - <seed>.sfc")]
        public string OutputFileV11 {
            get {
                return ((string)(this["OutputFileV11"]));
            }
            set {
                this["OutputFileV11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public string ControlsShot {
            get {
                return ((string)(this["ControlsShot"]));
            }
            set {
                this["ControlsShot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string ControlsJump {
            get {
                return ((string)(this["ControlsJump"]));
            }
            set {
                this["ControlsJump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string ControlsDash {
            get {
                return ((string)(this["ControlsDash"]));
            }
            set {
                this["ControlsDash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select")]
        public string ControlsItemSelect {
            get {
                return ((string)(this["ControlsItemSelect"]));
            }
            set {
                this["ControlsItemSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string ControlsItemCancel {
            get {
                return ((string)(this["ControlsItemCancel"]));
            }
            set {
                this["ControlsItemCancel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public string ControlsAngleUp {
            get {
                return ((string)(this["ControlsAngleUp"]));
            }
            set {
                this["ControlsAngleUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string ControlsAngleDown {
            get {
                return ((string)(this["ControlsAngleDown"]));
            }
            set {
                this["ControlsAngleDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Casual")]
        public string RandomizerDifficulty {
            get {
                return ((string)(this["RandomizerDifficulty"]));
            }
            set {
                this["RandomizerDifficulty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateSpoilerLog {
            get {
                return ((bool)(this["CreateSpoilerLog"]));
            }
            set {
                this["CreateSpoilerLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public decimal CustomNormalMissiles {
            get {
                return ((decimal)(this["CustomNormalMissiles"]));
            }
            set {
                this["CustomNormalMissiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal CustomSuperMissiles {
            get {
                return ((decimal)(this["CustomSuperMissiles"]));
            }
            set {
                this["CustomSuperMissiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal CustomPowerBombs {
            get {
                return ((decimal)(this["CustomPowerBombs"]));
            }
            set {
                this["CustomPowerBombs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public decimal CustomEnergyTanks {
            get {
                return ((decimal)(this["CustomEnergyTanks"]));
            }
            set {
                this["CustomEnergyTanks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomHiddenItems {
            get {
                return ((bool)(this["CustomHiddenItems"]));
            }
            set {
                this["CustomHiddenItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomRandomBlanks {
            get {
                return ((bool)(this["CustomRandomBlanks"]));
            }
            set {
                this["CustomRandomBlanks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomRandomNoBlanks {
            get {
                return ((bool)(this["CustomRandomNoBlanks"]));
            }
            set {
                this["CustomRandomNoBlanks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCustomSettings {
            get {
                return ((bool)(this["UseCustomSettings"]));
            }
            set {
                this["UseCustomSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Casual")]
        public string CustomRouteGen {
            get {
                return ((string)(this["CustomRouteGen"]));
            }
            set {
                this["CustomRouteGen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public decimal CustomNormalMissilesMax {
            get {
                return ((decimal)(this["CustomNormalMissilesMax"]));
            }
            set {
                this["CustomNormalMissilesMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal CustomSuperMissilesMax {
            get {
                return ((decimal)(this["CustomSuperMissilesMax"]));
            }
            set {
                this["CustomSuperMissilesMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal CustomPowerBombsMax {
            get {
                return ((decimal)(this["CustomPowerBombsMax"]));
            }
            set {
                this["CustomPowerBombsMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public decimal CustomEnergyTanksMax {
            get {
                return ((decimal)(this["CustomEnergyTanksMax"]));
            }
            set {
                this["CustomEnergyTanksMax"] = value;
            }
        }
    }
}
